# Generated by Django 3.1.5 on 2021-01-19 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemaoc', '0002_album_musician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
